version: "3.8"

services:
  react-native-app:
    build:
      context: .
    ports:
      - "8081:8081"  # Metro Bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo WebSocket
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    stdin_open: true
    tty: true
    command: ["npx", "expo", "start", "--tunnel"]
